import type { RuleIds, UserConfig } from "./types.js";

const DEFAULT_IGNORE = [
  "(^|/)node_modules/",
  "(^|/)(?:dist|build|\\.svelte-kit|\\.turbo)/",
  "(^|/)(?:coverage|test-results|playwright-report|storybook-static(?:-check)?)/",
  "^spec/book/",
  "\\.(?:spec|test)\\.[cm]?[jt]sx?$",
];

function rules(prefix: string): RuleIds {
  return {
    summary: `${prefix}-GOV-003`,
    governance: `${prefix}-GOV-001`,
    verification: `${prefix}-GOV-002`,
    book: `${prefix}-GOV-003`,
    bookIgnore: `${prefix}-GOV-008`,
    publicSurfaces: `${prefix}-GOV-003`,
    storybookCatalog: `${prefix}-GOV-009`,
    storybookMirrors: `${prefix}-CAT-005`,
    qmd: `${prefix}-GOV-005`,
    markdownlint: `${prefix}-GOV-001`,
    packageManifest: `${prefix}-GOV-003`,
    specFirst: `${prefix}-GOV-004`,
    internal: `${prefix}-GOV-003`,
  };
}

export const PRESETS: Record<string, UserConfig> = {
  "spec-validator": {
    preset: "spec-validator",
    idPattern: /^SV-[A-Z]+-\d{3}$/,
    specDir: "spec/src",
    requirementStyle: "heading",
    maxWords: 80,
    maxSentences: 4,
    minAcceptance: 2,
    maxAcceptance: 4,
    ruleIds: {
      summary: "SV-GOV-003",
      governance: "SV-GOV-001",
      verification: "SV-GOV-002",
      book: "SV-GOV-003",
      bookIgnore: "SV-GOV-005",
      publicSurfaces: "SV-GOV-003",
      storybookCatalog: "SV-VAL-001",
      storybookMirrors: "SV-VAL-001",
      qmd: "SV-QMD-001",
      markdownlint: "SV-CLI-003",
      packageManifest: "SV-ARCH-001",
      specFirst: "SV-GOV-004",
      internal: "SV-GOV-003",
    },
    validators: {
      summary: true,
      governance: { extras: ["AGENTS.md", "README.md"] },
      verification: {
        columns: 3,
        statuses: ["Implemented", "In progress", "Partial"],
        header: "Requirement",
      },
      book: true,
      qmd: { collection: "spec-validator" },
      markdownlint: { config: ".markdownlint-cli2.jsonc" },
      specFirst: {
        changeMap: "spec/src/spec-governance.md",
        ignore: DEFAULT_IGNORE,
        rules: [
          { pattern: "^src/(cli|argv|color|reporter)\\.ts$", chapters: ["spec/src/cli.md"] },
          { pattern: "^src/index\\.ts$", chapters: ["spec/src/architecture.md"] },
          { pattern: "^src/commands/(validate|check|list|build|first)\\.ts$", chapters: ["spec/src/cli.md"] },
          { pattern: "^src/(config|presets)\\.ts$", chapters: ["spec/src/configuration.md"] },
          { pattern: "^src/presets/", chapters: ["spec/src/configuration.md"] },
          { pattern: "^src/validators/", chapters: ["spec/src/validators.md"] },
          { pattern: "^src/(model|tracked-files|types|diagnostics|context)\\.ts$", chapters: ["spec/src/architecture.md"] },
          { pattern: "^src/commands/(doctor|init)\\.ts$", chapters: ["spec/src/doctor-and-init.md"] },
          { pattern: "^src/commands/search\\.ts$", chapters: ["spec/src/search-and-qmd.md"] },
          { pattern: "^src/commands/skill\\.ts$", chapters: ["spec/src/skill-and-agents.md"] },
          { pattern: "^skill/", chapters: ["spec/src/skill-and-agents.md"] },
          { pattern: "^(spec/book\\.toml|\\.qmd/index\\.ya?ml|\\.gitignore|AGENTS\\.md)$", chapters: ["spec/src/spec-governance.md"] },
          { pattern: "^package\\.json$", chapters: ["spec/src/architecture.md"] },
        ],
        protected: [
          "^src/",
          "^skill/",
          "^spec/book\\.toml$",
          "^package\\.json$",
          "^AGENTS\\.md$",
        ],
      },
    },
    check: { tests: "pnpm test" },
  },
  "design-core": {
    preset: "design-core",
    idPattern: /^DC-[A-Z]+-\d{3}$/,
    requirementStyle: "heading",
    ruleIds: {
      ...rules("DC"),
      bookIgnore: "DC-GOV-008",
      storybookCatalog: "DC-GOV-009",
      storybookMirrors: "DC-CAT-005",
    },
    validators: {
      summary: true,
      governance: { extras: ["AGENTS.md", "SPEC_MIGRATION.md", "README.md"] },
      verification: { columns: 3, statuses: ["Implemented", "In progress", "Partial"] },
      book: true,
      publicSurfaces: { map: "spec/public-surfaces.json" },
      storybookCatalog: { roots: ["src"], packageName: "@lapismd/design-core" },
      storybookMirrors: { style: "src-spec-mdx" },
      qmd: { collection: "design-core-spec" },
      specFirst: {
        changeMap: "spec/src/spec-governance.md",
        ignore: DEFAULT_IGNORE,
        rules: [
          { pattern: "^src/spec/.*\\.mdx$", chapters: ["spec/src/storybook-catalog.md"] },
          { pattern: "^src/shared/shadcn/", chapters: ["spec/src/shadcn"] },
          { pattern: "^src/shared/forms/", chapters: ["spec/src/forms/core-and-orchestrators.md"] },
          { pattern: "^src/shared/filter/", chapters: ["spec/src/filter.md"] },
          { pattern: "^src/shared/ai/", chapters: ["spec/src/ai.md"] },
          { pattern: "^src/shared/shell/", chapters: ["spec/src/shell.md"] },
          { pattern: "^src/shared/workspace/", chapters: ["spec/src/workspace/framework.md"] },
          { pattern: "^\\.storybook/", chapters: ["spec/src/storybook-catalog.md"] },
          { pattern: "^scripts/spec-validation/", chapters: ["spec/src/spec-governance.md"] },
          { pattern: "^package\\.json$", chapters: ["spec/src/architecture.md", "spec/src/packages.md"] },
        ],
        protected: ["^src/", "^\\.storybook/", "^scripts/", "^package\\.json$"],
      },
    },
  },
  "lapis-notes": {
    preset: "lapis-notes",
    idPattern: /^LN-[A-Z]+-\d{3}$/,
    requirementStyle: "table",
    minAcceptance: 0,
    maxAcceptance: 20,
    ruleIds: {
      ...rules("LN"),
      bookIgnore: "LN-GOV-007",
      storybookCatalog: "LN-GOV-023",
      qmd: "LN-GOV-020",
    },
    validators: {
      summary: true,
      governance: { extras: ["AGENTS.md", "MIGRATION.md"] },
      verification: {
        columns: 4,
        statuses: ["Planned", "Implemented", "In progress", "Partial"],
        header: "ID",
      },
      book: true,
      storybookCatalog: { roots: ["stories", "packages"] },
      qmd: { collection: "lapis-spec" },
      specFirst: {
        changeMap: "spec/src/spec-governance.md",
        ignore: DEFAULT_IGNORE,
        rules: [
          { pattern: "^packages/", chapters: ["spec/src/packages.md"] },
          { pattern: "^scripts/spec-validation/", chapters: ["spec/src/spec-governance.md"] },
          { pattern: "^\\.qmd/index\\.ya?ml$", chapters: ["spec/src/spec-governance.md"] },
        ],
        protected: ["^packages/", "^scripts/", "^package\\.json$"],
      },
    },
  },
  mira: {
    preset: "mira",
    idPattern: /^MIRA-[A-Z]+-\d{3}$/,
    requirementStyle: "table",
    minAcceptance: 0,
    maxAcceptance: 20,
    ruleIds: rules("MIRA"),
    validators: {
      summary: true,
      governance: { extras: ["AGENTS.md"] },
      verification: { columns: 3, statuses: ["Implemented", "In progress", "Partial"] },
      book: true,
      storybookMirrors: { style: "stories-spec", directory: "stories/spec" },
      markdownlint: { config: ".markdownlint-cli2.jsonc" },
      specFirst: {
        changeMap: "spec/src/spec-governance.md",
        ignore: [...DEFAULT_IGNORE, "^tests/", "^stories/(?!catalog/)"],
        rules: [
          { pattern: "^packages/(?:plugin-ai|mira-plugin-ai)/", chapters: ["spec/src/packages.md", "spec/src/plugins/ai.md"] },
          { pattern: "^packages/(?:plugin-mermaid|mira-plugin-mermaid)/", chapters: ["spec/src/packages.md", "spec/src/plugins/mermaid.md"] },
          { pattern: "^packages/(?:mira|mira-editor)/", chapters: ["spec/src/packages.md"] },
          { pattern: "^scripts/check-spec", chapters: ["spec/src/spec-governance.md"] },
        ],
        protected: ["^packages/", "^scripts/", "^package\\.json$"],
      },
    },
  },
  "visual-delta": {
    preset: "visual-delta",
    idPattern: /^VD-[A-Z]+-\d{3}$/,
    requirementStyle: "table",
    minAcceptance: 0,
    maxAcceptance: 20,
    ruleIds: rules("VD"),
    validators: {
      summary: true,
      governance: { extras: ["AGENTS.md", "CHANGELOG.md", "DEVELOPMENT.md", "README.md"] },
      verification: { columns: 3, statuses: ["Implemented", "In progress", "Partial", "Conforming"] },
      book: true,
      markdownlint: { config: ".markdownlint-cli2.jsonc" },
      specFirst: {
        changeMap: "spec/src/spec-governance.md",
        ignore: DEFAULT_IGNORE,
        rules: [
          { pattern: "^src/", chapters: ["spec/src/architecture.md"] },
          { pattern: "^scripts/check-spec", chapters: ["spec/src/spec-governance.md"] },
          { pattern: "^package\\.json$", chapters: ["spec/src/spec-governance.md"] },
        ],
        protected: ["^src/", "^scripts/", "^package\\.json$", "^AGENTS\\.md$"],
      },
    },
  },
  "cv-roles": {
    preset: "cv-roles",
    idPattern: /^(?:LN-(?:CV|ROLE)|LPR-SPEC)-\d{3}$/,
    requirementStyle: "table",
    minAcceptance: 0,
    maxAcceptance: 20,
    ruleIds: {
      summary: "LPR-SPEC-003",
      governance: "LPR-SPEC-003",
      verification: "LPR-SPEC-003",
      book: "LPR-SPEC-003",
      bookIgnore: "LPR-SPEC-003",
      publicSurfaces: "LPR-SPEC-003",
      storybookCatalog: "LPR-SPEC-003",
      storybookMirrors: "LPR-SPEC-003",
      qmd: "LPR-SPEC-003",
      markdownlint: "LPR-SPEC-003",
      packageManifest: "LPR-SPEC-003",
      specFirst: "LPR-SPEC-003",
      internal: "LPR-SPEC-003",
    },
    validators: {
      summary: true,
      verification: { columns: 3, statuses: ["Implemented", "In progress", "Partial"] },
      book: true,
      packageManifest: {
        name: "@lapis-notes/lapis-plugin-cv-roles",
        version: "0.1.0",
        privateAllowed: false,
        portableDependencies: true,
        manifestPath: "manifest.json",
        manifest: {
          id: "roles",
          distribution: "first-party-external",
          provenance: "official",
          enabledByDefault: true,
        },
      },
      specFirst: {
        changeMap: "spec/src/spec-governance.md",
        ignore: DEFAULT_IGNORE,
        rules: [
          { pattern: "^src/", chapters: ["spec/src/roles-plugin.md"] },
          { pattern: "^(?:scripts/spec-validation/|AGENTS\\.md$)", chapters: ["spec/src/spec-governance.md"] },
        ],
        protected: ["^src/", "^manifest\\.json$", "^package\\.json$"],
      },
    },
  },
};

export function getPreset(name: string): UserConfig {
  const preset = PRESETS[name];
  if (!preset) throw new Error(`unknown preset: ${name}`);
  return structuredClone(preset);
}
